config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  resources :admins
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :albums do
    member do
      delete :delete_image
    end
  end
  
  get '/about' => 'pages#about'
  get '/members' => 'pages#members'
  get '/mission' => 'pages#mission'
  get '/outreach' => 'pages#outreach'
  get '/sponsorship' => 'pages#sponsorship'
  get '/contact' => 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    before_save {self.username = username.downcase}
    has_secure_password
end

app/models/album.rb
class Album < ApplicationRecord
    has_many_attached :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)

    if @admin.save
      log_in(@admin)
      redirect_to @admin
    else
      render 'new'
    end
  end

  def edit
  end

  def index
  end

  def show
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:username,:password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      redirect_to root_path
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
  end

  def index
    @albums = Album.all
  end

  def delete_image
    @album_image = ActiveStorage::Attachment.find(params[:id])
    @album_image.purge
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  def album_params
    params.require(:album).permit(:title,images:[])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def members
  end  

  def mission
  end

  def outreach
  end

  def sponsorship
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @admin = Admin.find_by(username: params[:session][:username])

    if @admin && @admin.authenticate(params[:session][:password])
      log_in(@admin)
      redirect_to @admin
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(admin)
        session[:admin_id] = admin.id
    end

    def logged_in?
        !current_admin.nil?
    end

    def current_admin
        @current_admin ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id]
    end

    def log_out
        session.delete(:admin_id)
        @current_admin = nil
    end
end

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>

app/views/admins/new.html.erb
<h1>Register a new admin</h1>
<%= form_for(@admin) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %><br/>
    <%= f.label :password %>
    <%= f.password_field :password %><br/>

    <%= f.submit 'Create admin' %>
<% end %>

app/views/admins/show.html.erb
<% if logged_in? %>
<h1>Admin Show Page</h1>
<%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
<h1>Log In</h1>
<% end %>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/index.html.erb
<h1>Albums</h1>
<% @albums.each do |album| %>
    <%= link_to album.title, album %> | <%= link_to "Delete", album_url(album.id), method: :delete %>
<% end %>

app/views/albums/new.html.erb
<h1>Create new album</h1>
<%= form_for(@album) do |f| %>
    <%= f.label :title %>:
    <%= f.text_field :title %><br/><br/>
    <%= f.file_field :images, :multiple=>true %><br/><br/>
    <%= f.submit "Create Album" %>
<% end %>

app/views/albums/show.html.erb
<h1 id="album-title"><%= @album.title %></h1>
<% if @album.images.attached? %>
<div class="album-grid-container">
<% @album.images.each do |i| %>
    <div class="album-grid-item">
        <%= image_tag i %>
        <%= link_to image_tag('https://img.icons8.com/plasticine/100/000000/trash--v2.png', :class => "trash-icon"), delete_image_album_url(i.id),method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= yield :title %></title>

    <link rel="icon" href="<%= yield :favicon %>" type="image/png"/>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="scroll-active">
    <%= react_component('Navbar') %>
    <div class="hidden-div"></div>
    <!-- The above div is here to fix the page flow disruption caused
    by the absolute positioned navbar -->
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section style="position:relative;margin:10% auto;text-align:center;max-width:100%;">
<img style="width:50%" src="https://i.ibb.co/WxZK5JG/ezgif-com-crop.gif"/>
</section>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section class="contact-hero">
  <h2>Contact Us...</h2>
  <img src="https://i.ibb.co/fpFK8wL/contact-hero.png"/>
</section>

<section class="member-section">
  <h2>For Members...</h2>

    <p id="member-info">Within HawkWorks, our members work sporadically<br/>
throughout the week but we generally meet every<br/>
<span style="font-weight:bold;text-decoration:underline;font-style:italic">Wednesday</span> on Structural Testing and Student Projects<br/>
(STSP) Building at West Campus from <span style="font-weight:bold;text-decoration:underline;font-style:italic">6:00 pm</span> Central<br/>
Standard Time at:<br/><br/>

<span style="font-weight:bold;font-style:italic">Structural Testing and Student Projects</span><br/>

2107 Becker Drive,<br/>

Lawrence, KS 66046<br/><br/>

To get to STSP:<br/>

1. From Iowa Street, turn West on 21st Street<br/>

2. Make left onto Becker Drive<br/>

3. Follow the drive to parking lot 302<br/>

* A KU Yellow Parking Pass allows you to park
in lot<br/>302<br/>

* Bus 41 can also take you to lot 302<br/><br/>

A keycard (obtained through KU ID) is needed to enter the
building.<br/><br/>

Access to the facility will be granted based on frequency of
involvement in HawkWorks and its projects.<br/><br/>

Please note, the STSP facility is used only for working on
HawkWorks projects and does not accept any packages. A separate shipping address is provided below.</p>
  
  <section id="map-section">
  <img id="member-imgone" src="https://i.ibb.co/XjN4Hkq/stsp-map.png"/>
  <p class="image-caption">Map to Structural Testing and Student Projects Building</p>
  </section>
  
  <section id="stspbuilding-section">
  <img id="member-imgtwo" src="https://i.ibb.co/G7CkFKc/stsp-building.png"/>
  <p class="image-caption">Structural Testing and Student Projects Building at West Campus</p>
  </section>

</section>

<section class="nonmember-section">
  <h2>For everyone else...</h2>

<p id="nonmember-info1"><span style="font-weight:bold;font-style:italic">E-Mail</span><br/><br/>

For all inquiries including outreach,
marketing, membership, etc HawkWorks can be
reached through:<br/><br/>

<a href="mailto:hawkworks@ku.edu">hawkworks@ku.edu</a><br/><br/>

Please provide your full name and your inquiry in the subject.<br/><br/>

Please give HawkWorks several days to respond to
your e-mail.<br/><br/>

Due to a high volume of e-mails, HawkWorks is not able to
guarantee a response to every inquiry. Please resend
your e-mail to increase your chances of a getting a response.<br/><br/>

*For safety and security, HawkWorks will not
provide any personal information on any persons.</p>

<p id="nonmember-info2"><span style="font-weight:bold;font-style:italic">Shipping Address</span><br/><br/>

For all items that need to be shipped to HawkWorks,
please send it to the address below:<br/><br/>

<span style="font-weight:bold;font-style:italic">HawkWorks</span><br/>

1530 West 15th Street<br/>

3138 Learned Hall<br/>

Lawrence, KS 66046<br/><br/>

Please indicate your full name, your company (if
any) and provide a return address.<br/><br/>

*For safety and security, HawkWorks will not
provide any personal information on any persons.</p>

<p id="disclaimer">
Please note the contact information provided above is for serious inquiries only. Any ill-intentioned message or suspicious package sent to HawkWorks
WILL BE HANDED to proper authorities and HawkWorks will fully participate with the investigation.
<br/><br/>
*HawkWorks may provide personal information of the individuals or company to the proper authorities if such information is required to cooperate in the
investigation.
</p>

</section>

app/views/pages/home.html.erb
<% provide(:title, "HawkWorks") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section class="hero-section">
  <img src="https://i.ibb.co/XZVqD5p/hero-one.png"/>
  <p><a href="/about">Overkill is underrated!</a><br/>
  <span>University of Kansas' own advanced STEM team.</span>
  </p>
</section>

<section class="hero-section-two">
  <img src="https://i.ibb.co/m5QcwMH/hero-two.png" />
  <p>Innovative,<br/>interdisciplinary<br/>engineering <a href="/mission">systems</a><br/>
  <span>HawkWorks live to conceptualize,<br/>
  design, manufacture and<br/>demonstrate our projects.</span>
  </p>
</section>

<section class="hero-section-three">
  <img src="https://i.ibb.co/ZYVfGBc/hero-three.png" />
  <p>Analytical approach to solutions</p>
</section>

<section class="hero-section-four">
  <img src="https://i.ibb.co/9NbHY6s/hero-four.png" />
  <p>Real Hands-On Experience....</p>
</section>

<section class="hero-section-five">
  <img src="https://i.ibb.co/6PGJNDZ/hero-five.png" />
  <p><a href="/outreach">Demonstrating</a> HawkWorks projects<br/> and representing KU,
  both locally<br/> and nationally</p>
</section>

<section class="hero-section-six">
  <img src="https://i.ibb.co/bvVmFGP/hero-six.png" />
  <p>Think you have what it takes to be part of an autonomous <a href="/contact">team?</a></p>
</section>

app/views/pages/mission.html.erb
<% provide(:title, "Projects") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section style="position:relative;margin:10% auto;text-align:center;max-width:100%;">
<img style="width:50%" src="https://i.ibb.co/WxZK5JG/ezgif-com-crop.gif"/>
</section>

app/views/pages/outreach.html.erb
<% provide(:title, "Outreach") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section class="outreach-section-one">
  <img src="https://i.ibb.co/LQMkw4p/outreach-hero-one-opac.png"/>
  
  <h2>Demonstrating our projects to inspire STEM projects...</h2>
  
  <p class="outreach-capone">“Their musical Tesla Coil shooting out lightening bolts in tune with notes played on an electric
keyboard seemed to do the trick.”<br/><br/>
-<a target="_blank" href="https://www2.ljworld.com/news/2016/feb/25/too-cool-kids-ignore-ku-engineering-expo-draws-tho/">Sara Shepherd – Lawrence Journal, 2016</a>
  </p>
  
  <p class="outreach-captwo">“....so in order to get a video of the lightning, striking within the inches of our face without
risking cardiac arrest, we are stepping into a Faraday Cage.”<br/><br/>
-<a target="_blank" href="https://www.youtube.com/watch?v=wfYLE1aAsXs">Hank Schyma – Pecos Hank, 2017</a>
  </p>

  <p id="hawkworks-outreachinfo">
HawkWorks demonstrates its projects in local and national STEM events
to educate and inspire everyone to build cool stuff. Within Lawrence, we have
demonstrated several of our projects in several local events like the Hillcrest
Elementary’s Science Night, Eudora Elementary’s Science Fair, Prairie Park
Elementary’s Science Discovery Day, etc. Hawkworks also demonstrated in
national events and conferences like Maker Faire Kansas City, Confabullaryum
and French Innovation Week in Chicago.<br/><br/>

<b>Check out some of the albums from previous Hawkworks Outreach Events below!</b>
  </p>

</section>

app/views/pages/sponsorship.html.erb
<% provide(:title, "Sponsorship") %>
<% provide(:favicon, "https://image.ibb.co/dZEZsA/spinner.png") %>

<section style="position:relative;margin:10% auto;text-align:center;max-width:100%;">
<img style="width:50%" src="https://i.ibb.co/WxZK5JG/ezgif-com-crop.gif"/>
</section>